---
title: "Robbie_Spotify_Minning"
author: "R Freeman"
date: "8/18/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Minning the Spotify data via API 

```{r}

devtools::install_github('charlie86/spotifyr')
library(spotifyr)

#set system enviroment variables for client ID and Secret ID
Sys.setenv(SPOTIFY_CLIENT_ID = '6b99e144dd674a0cba426bc94c823929')
Sys.setenv(SPOTIFY_CLIENT_SECRET = '44727842431e4f3cb1909db30515aa70')

access_token <- get_spotify_access_token()

#pull in artist metrics such as genere, num followers, and popularity
for (i in 1:nrow(spotify_artists)) {
  if (i == 1){
    numFollowers <- get_artists(as.character(spotify_artists$dbname[i]))
  }else {
    tryCatch({
      numFollowers <- rbind(numFollowers, get_artists(as.character(spotify_artists$dbname[i])))},error=function(cond)
      {
        NA
      })
  }
  cat(paste0('\nFinished: ', i, ". Starting next loop on " , i+1, sep =' '))
}

#pull in album audio features 
for (i in 1:nrow(spotify_artists)) {
  if (i == 1){
    final_data <- get_artist_audio_features(as.character(spotify_artists$dbname[i]))
  }else {
    tryCatch({
      final_data <- rbind(final_data, get_artist_audio_features(as.character(spotify_artists$dbname[i])))},error=function(cond)
      {
        NA
      })
  }
  cat(paste0('\nFinished: ', i, ". Starting next loop on " , i+1, sep =' '))
}
```

Create a training and test set 

```{r}
library(dplyr)

#drop na rows 

final_data2 <-na.omit(final_data)

#75% of the sample size
smp_size <- floor(0.75 * nrow(final_data2))

#set the seed to make partition reproducible
set.seed(123)
train_ind <- sample(seq_len(nrow(final_data2)), size = smp_size)

train <- final_data2[train_ind, ]
test <- final_data2[-train_ind, ]
```

Building the regression model 

```{r}
library(performanceEstimation)

attach(train)

#multiple linear regression model
linearModel <- lm(track_popularity + loudness + danceability + energy + acousticness +liveness + instrumentalness, data = train)

linearPred <- predict(linearModel, newdata = test)
lmModelAccuracyAdjusted <- accuracy(test$artist_popularity, linearPred)

#create dataset for Multiple Linear Regression
lmPred <- data.frame(linearPred)
lmPred$actual <- test$artist_popularity

```
   


```




